[project]
name = "prompt-genie"
version = "0.0.0"
dependencies = ["g4f[api]", "curl_cffi", "prompt-poet", "chainlit"]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project.scripts]
editor = "app:main"